spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    mode: HTML5

mybatis:
  type-aliases-package: top.xiaoming.demo.springbootdemo.domain.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql